const ActionsType = {
  CREATE_PROJECT: 'CREATE_PROJECT',
  SET_PROJECTS: 'SET_PROJECTS',
  SELECT_PROJECTS: 'SELECT_PROJECTS',
  REMOVE_SELECT_PROJECTS: 'REMOVE_SELECT_PROJECTS',
};

export default ActionsType;
